project:
  type: website

website:
  site-url: https://zed4zee.github.io/personal
  search:
    location: navbar
    type: overlay
  title: "Blog"
  favicon: favicon.jpg
  navbar:
    right:
      - icon: github
        href: https://github.com/zed4zee
      - icon: rss
        href: index.xml
  page-footer:
    center:
      - text: © 2023-present.
  page-navigation: true
  reader-mode: true
  back-to-top-navigation: true
format:
  html:
    theme: default
    toc: true
